### ISSUE TITLE
Unable to load API key/secret ("The environment variables are invalid")

### ISSUE THREAD

**Issue by ChristopherBull** [iorate/semantic-release-amo#1]
I'm having trouble authenticating within this project. I have added the key and secret to my repository, as you can see here:

![image](https://github.com/user-attachments/assets/0af19ecd-c35a-4aec-af45-835dc388a391)

The error messages do not indicate if authentication failed or if the environment variables could not be found. Does the project load Environment Secrets or does it load Environment Variables?

Here is my GitHub Action release log:
https://github.com/ChristopherBull/Clear-Links/actions/runs/10753280933/job/29822843847

```sh
Validation error: Required at "AMO_API_KEY"; Required at "AMO_API_SECRET"

AggregateError: 
    SemanticReleaseError: The environment variables are invalid.
        at verifyConditions (/home/runner/work/Clear-Links/Clear-Links/node_modules/semantic-release-amo/dist/verify-conditions.js:47:21)
        at async validator (file:///home/runner/work/Clear-Links/Clear-Links/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
        at async file:///home/runner/work/Clear-Links/Clear-Links/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
        at async Promise.all (index 0)
        at async next (file:///home/runner/work/Clear-Links/Clear-Links/node_modules/p-reduce/index.js:15:44)
    at file:///home/runner/work/Clear-Links/Clear-Links/node_modules/semantic-release/lib/plugins/pipeline.js:55:13
    at async pluginsConfigAccumulator.<computed> [as verifyConditions] (file:///home/runner/work/Clear-Links/Clear-Links/node_modules/semantic-release/lib/plugins/index.js:87:11)
    at async run (file:///home/runner/work/Clear-Links/Clear-Links/node_modules/semantic-release/index.js:106:3)
    at async Module.default (file:///home/runner/work/Clear-Links/Clear-Links/node_modules/semantic-release/index.js:278:22)
    at async default (file:///home/runner/work/Clear-Links/Clear-Links/node_modules/semantic-release/cli.js:55:5) {
  errors: [
    SemanticReleaseError: The environment variables are invalid.
        at verifyConditions (/home/runner/work/Clear-Links/Clear-Links/node_modules/semantic-release-amo/dist/verify-conditions.js:47:21)
        at async validator (file:///home/runner/work/Clear-Links/Clear-Links/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
        at async file:///home/runner/work/Clear-Links/Clear-Links/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
        at async Promise.all (index 0)
        at async next (file:///home/runner/work/Clear-Links/Clear-Links/node_modules/p-reduce/index.js:15:44) {
      code: 'EINVALIDENV',
      details: 'Validation error: Required at "AMO_API_KEY"; Required at "AMO_API_SECRET"',
      semanticRelease: true,
      pluginName: 'semantic-release-amo'
    }
  ]
}
Error: Process completed with exit code 1.
```

Thanks for this project!

**Comment by ChristopherBull** [comment]
Sincere apologies - it was of course my simple mistake. I forgot to add env passthrough in my yaml workflows:
```yaml
env:
    AMO_API_KEY: ${{ secrets.AMO_API_KEY }}
    AMO_API_SECRET: ${{ secrets.AMO_API_SECRET }}
```
